### ISSUE TITLE
Maximum recursion depth exceeded with mutual membership.

### ISSUE THREAD

**Issue by OrangeNote** [catseye/ALPACA#3]
I don't know if mutual membership is useful when defining a real cellular automata, but in this case alpaca fails because it doesn't know if a class has been already checked (but I think it should), so the recursion goes forever:
```
class A is B to X when false;
class B is A to X when false;

state Blank " ";
state X "*" is A

begin
*
```

**Comment by cpressey** [comment]
The patch seems to address the problem at runtime, but, I also think the "mutual membership" situation simply doesn't make any sense.  (In an OO language like Java, would you ever have class A inherit from class B, _and_ class B inherit from class A?)  I think it would probably be better to statically prohibit it, i.e. detect cycles in the class-containment tree at compile-time, and issue an error if there are any.

**Comment by cpressey** [comment]
Having thought about it more... I still don't think it makes _much_ sense to do this, but I also don't think the language needs the extra complication of saying that the situation is required to be detected statically, and there might be _some_ sense in which doing this is, if not useful, then at least interesting.

So I think #4 is fine, and I'll merge it in, and I'll look to incorporate those changes, and a test, in 1.1.

Thanks!
